# Copyright (c) 2023 tinyVision.ai Inc.
# SPDX-License-Identifier: MIT

manifest:

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: Emcraft
      url-base: https://github.com/EmcraftSystems

  projects:
    - name: zephyr-tnv
      remote: Emcraft
      revision: emcraft-dev
      import:
        name-allowlist:
          - zephyr
