# Copyright (c) 2023-2024 tinyVision.ai Inc.
# SPDX-License-Identifier: MIT

manifest:

  projects:
    - name: zephyr
      url: git@github.com:tinyvision-ai-inc/zephyr_private
      revision: 96d8c0ae113
      import:
        name-allowlist:
          - zephyr
