# Copyright (c) 2023-2024 tinyVision.ai Inc.
# SPDX-License-Identifier: MIT

manifest:

  projects:
    - name: zephyr
      url: https://github.com/tinyvision-ai-inc/zephyr_private
      revision: tinyclunx33
      import:
        name-allowlist:
          - zephyr
