# Copyright (c) 2023-2024 tinyVision.ai Inc.
# SPDX-License-Identifier: Apache-2.0

manifest:
  projects:

    - name: zephyr
      url: git@github.com:tinyvision-ai-inc/zephyr
      revision: usb3
      import:
        name-allowlist:
          - zephyr

    - name: tinyclunx33_sdk
      url: git@github.com:tinyvision-ai-inc/zephyr_internal
      revision: tinyclunx33_sdk
